Repository ucsb-cs156-s25/proj-dining-s25-04, pull requests merged in 2025-05, with the labels that each got.

#29 Added Endpoint for Individual Review
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: 10

#31 Create a Review Table
  frontend/src/fixtures/reviewFixtures.js
  frontend/src/main/components/Reviews/ReviewTable.js
  frontend/src/stories/components/Reviews/ReviewsTable.stories.js
  frontend/src/tests/components/Reviews/ReviewsTable.test.js
Labels: 10

#34 Removed longitude and latitude columns from the dining commons table
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
Labels: 5

#35 Added a placeholder create page for posting reviews + tests
  frontend/src/App.js
  frontend/src/main/pages/Reviews/ReviewsCreatePage.js
  frontend/src/tests/pages/Reviews/ReviewsCreatePage.test.js
Labels: Merge Candidate-CI, 10

#33 Add an Individual Menu Item Endpoint
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsControllerTests.java
Labels: Merge Candidate-CI, 10

#41 Repeat the Deploy step in Github Actions to avoid failures
  .github/workflows/04-gh-pages-redeploy-part-2.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/53-chromatic-main-branch.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
Labels: Merge Candidate-CI, 10, HOLD-Github Issues

#32 Add a Placeholder page for Reviews
  frontend/src/App.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/main/pages/Reviews/ReviewsForMenuItemPage.js
  frontend/src/stories/pages/Reviews/ReviewsForMenuItemPage.stories.js
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
  frontend/src/tests/pages/Reviews/ReviewsForMenuItemPage.test.js
Labels: Merge Candidate-CI, 10

#42 Auto-Approve reviews without comments
  src/main/java/edu/ucsb/cs156/dining/controllers/ReviewController.java
  src/test/java/edu/ucsb/cs156/dining/controllers/ReviewControllerTests.java
Labels: Merge Candidate-CI, 10

#44 Add Individual Review page
  frontend/src/main/pages/Reviews/ReviewsForMenuItemPage.js
  frontend/src/stories/pages/Reviews/ReviewsForMenuItemPage.stories.js
  frontend/src/tests/pages/Reviews/ReviewsForMenuItemPage.test.js
Labels: Merge Candidate-CI, 10

#36 Updated to react router v7 from v6
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/main/components/DiningCommons/DiningCommonsTable.js
  frontend/src/main/components/Meal/MealTable.js
  frontend/src/main/components/MenuItem/MenuItemTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Meal/MealTimesPage.js
  frontend/src/main/pages/MenuItem/MenuItemPage.js
  frontend/src/main/pages/Moderate.js
  frontend/src/main/pages/MyReviews/MyReviewsIndexPage.js
  frontend/src/main/pages/Placeholder/PlaceholderIndexPage.js
  frontend/src/main/pages/Reviews/ReviewsCreatePage.js
  frontend/src/main/pages/Reviews/ReviewsEditPage.js
  frontend/src/main/pages/Reviews/ReviewsForMenuItemPage.js
  frontend/src/main/utils/currentUser.js
  frontend/src/setupTests.js
  frontend/src/tests/components/DiningCommons/DiningCommonsTable.test.js
  frontend/src/tests/components/Meal/MealTable.test.js
  frontend/src/tests/components/MenuItem/MenuItemTable.test.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
  frontend/src/tests/pages/HomePage.test.js
  frontend/src/tests/pages/Meal/MealTimesPage.test.js
  frontend/src/tests/pages/MenuItem/MenuItemPage.test.js
  frontend/src/tests/pages/Moderate.test.js
  frontend/src/tests/pages/MyReviews/MyReviewsIndexPage.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderCreatePage.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderEditPage.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderIndexPage.test.js
  frontend/src/tests/pages/ProfilePage.test.js
  frontend/src/tests/pages/Reviews/ReviewsCreatePage.test.js
  frontend/src/tests/pages/Reviews/ReviewsEditPage.test.js
  frontend/src/tests/pages/Reviews/ReviewsForMenuItemPage.test.js
  frontend/src/tests/utils/currentUser.test.js
  frontend/src/tests/utils/systemInfo.test.js
  frontend/src/tests/utils/useBackend.test.js
  src/main/java/edu/ucsb/cs156/dining/controllers/UCSBDiningMenuItemsController.java
Labels: Merge Candidate-CI, 10

#37 Fahim - Moderator Frontend
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Moderate.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Moderate.test.js
Labels: Merge Candidate-CI, 10

#45 Ethan: Added Form for Posting a Review
  frontend/src/fixtures/reviewFixtures.js
  frontend/src/main/components/Reviews/ReviewsForm.js
  frontend/src/stories/components/Reviews/ReviewsForm.stories.js
  frontend/src/tests/components/Reviews/ReviewsForm.test.js
Labels: Ready-For-Staff
